# Generated by Django 5.1.2 on 2024-11-06 19:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("space_data", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="launchmission",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
