# Generated by Django 5.1.2 on 2024-11-06 20:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("space_data", "0002_launchmission_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rocketconfiguration",
            name="rocket_diameter",
        ),
    ]
