# Generated by Django 5.1.2 on 2024-11-07 14:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("space_data", "0003_remove_rocketconfiguration_rocket_diameter"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vehiclerecoverymethod",
            name="location",
        ),
    ]
