# Generated by Django 5.1.2 on 2024-11-07 14:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("space_data", "0004_remove_vehiclerecoverymethod_location"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="payloadgroup",
            name="idx_pg_company_id",
        ),
        migrations.RemoveField(
            model_name="payloadgroup",
            name="payload_type",
        ),
    ]
