# Generated by Django 5.1.2 on 2024-11-09 22:11

import space_data.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("space_data", "0005_remove_payloadgroup_idx_pg_company_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="url",
            field=models.ImageField(
                upload_to=space_data.models.get_unique_image_upload_path
            ),
        ),
    ]
